#include <bits/stdc++.h>
using namespace std;

/*
    Spell Checker
    -------------
    - Load dictionary into unordered_set for O(1) lookup.
    - A word is correct if it exists in dictionary.
    - Suggestions are generated by:
        * Inserting a-z at each position
        * Deleting one character
        * Replacing a character with a-z
      All operations give edit-distance-1 variants.
*/

class SpellChecker {
private:
    unordered_set<string> dict;

public:
    SpellChecker(const vector<string>& words) {
        for (auto &w : words) dict.insert(w);
    }

    bool isCorrect(const string& word) {
        return dict.count(word) > 0;
    }

    vector<string> getSuggestions(const string& word) {
        vector<string> res;
        unordered_set<string> seen;

        int n = word.size();

        // 1. Deletions
        for (int i = 0; i < n; i++) {
            string s = word.substr(0, i) + word.substr(i + 1);
            if (dict.count(s) && !seen.count(s)) {
                seen.insert(s);
                res.push_back(s);
            }
        }

        // 2. Replacements
        for (int i = 0; i < n; i++) {
            for (char c = 'a'; c <= 'z'; c++) {
                if (c == word[i]) continue;
                string s = word;
                s[i] = c;
                if (dict.count(s) && !seen.count(s)) {
                    seen.insert(s);
                    res.push_back(s);
                }
            }
        }

        // 3. Insertions
        for (int i = 0; i <= n; i++) {
            for (char c = 'a'; c <= 'z'; c++) {
                string s = word.substr(0, i) + c + word.substr(i);
                if (dict.count(s) && !seen.count(s)) {
                    seen.insert(s);
                    res.push_back(s);
                }
            }
        }

        return res;
    }
};

// ------------------ DEMO USAGE -------------------

int main() {
    vector<string> dictionary = {
        "hello", "help", "shell", "held", "helmet", "hero", "hell"
    };

    SpellChecker sp(dictionary);

    string query = "helo";

    if (sp.isCorrect(query)) {
        cout << query << " is correctly spelled\n";
    } else {
        cout << query << " is incorrect. Suggestions:\n";
        for (auto &s : sp.getSuggestions(query)) {
            cout << s << " ";
        }
        cout << "\n";
    }

    return 0;
}
